# Generated by Django 3.2 on 2021-04-19 20:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base_app', '0003_auto_20210419_2258'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cart',
            options={'verbose_name': 'Корзину', 'verbose_name_plural': 'Корзины'},
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Категорию', 'verbose_name_plural': 'Категории'},
        ),
        migrations.AlterModelOptions(
            name='customer',
            options={'verbose_name': 'Покупателя', 'verbose_name_plural': 'Покупатели'},
        ),
        migrations.AlterModelOptions(
            name='subcategory',
            options={'verbose_name': 'Подкатегорию', 'verbose_name_plural': 'Подкатегории'},
        ),
    ]
