# Generated by Django 3.2 on 2021-04-19 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_app', '0004_auto_20210419_2300'),
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Новость')),
                ('description', models.TextField(verbose_name='Содержание')),
                ('image', models.ImageField(upload_to='', verbose_name='Изображение')),
                ('published', models.DateTimeField(auto_now=True, verbose_name='Дата публикации')),
                ('slug', models.SlugField(unique=True)),
            ],
            options={
                'verbose_name': 'Новость',
                'verbose_name_plural': 'Новости',
            },
        ),
    ]
